### ISSUE TITLE
Error produced by `ember-ajax` references Ember Data

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-ajax#82]
> Ember Data Request GET https://taskaparilla.stamplayapp.com/auth/v1/logout returned a 0 Payload (Empty Content-Type)

This is very confusing because no Ember Data is involved.

**Comment by alexlafroscia** [comment]
Which version are you using?  This was an issue raised by the fact that the networking code here was originally lifted from Ember Data's `RESTAdapter`.  We fixed this issue (as far as I know) in the `2.0` release; can you try the latest beta and let me know if the issue persists?

**Comment by lolmaus** [comment]
Uhm, not sure. I've been using 0.x, then upgraded to 2.x and I don't remember which version it happened or how to reproduce the problem.

As you migrated away from Ember Data's `RESTAdapter`, I assume this is solved.

**Comment by sandstrom** [comment]
@alexlafroscia I'm seeing this on 2.1, and it's to endpoints that are never hit by Ember Data (there isn't even a DS model corresponding to the endpoints where I see this).

**Comment by alexlafroscia** [comment]
Huh, indeed you're right, this is still an issue. I'll get a PR together to fix that up, thanks for catching that @sandstrom!

**Comment by lolmaus** [comment]
Told ya. )

**Comment by lolmaus** [comment]
:bow:

**Comment by sandstrom** [comment]
@alexlafroscia Thanks! ⛵
